name: Android Build (Release)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew

      - name: Decode advance_native.pfx keystore to app folder
        run: |
          mkdir -p app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/advance_native.pfx

      - name: Create signing.properties at root
        run: |
          echo "storeFile=app/advance_native.pfx" > signing.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> signing.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> signing.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> signing.properties

      - name: Build Signed AAB (Release)
        run: ./gradlew :app:bundleRelease --stacktrace

      - name: List AAB Output
        run: find app/build/outputs/bundle/release -name "*.aab"

      - name: Upload Signed AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/*.aab
